version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pdv-db
    environment:
      POSTGRES_DB: Pdv
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: database123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pdv-app:
    build: .
    container_name: pdv-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Pdv?currentSchema=public
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: database123
    depends_on:
      - postgres

volumes:
  pgdata:
