spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/Pdv
    username: postgres
    password: database123
    driver-class-name:  org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true